//! Display layout: framebuffer, `DrawTarget`, the profont/fub glyph atlases
//! converted from U8g2, the ported `DisplayLayoutUtils` helpers, and the six
//! templates.
//!
//! # Rules
//!
//! * Portable and `no_std`: it renders into a byte buffer, so the whole thing is
//!   golden-image testable on the host (R1-04 / R2-10) with no hardware.
//! * The AGENTS.md OLED rules apply here as assertions, not as conventions:
//!   everything fits 128x64, no rows overlap, counting fields use a fixed pixel
//!   width so digits do not shift, a bar and its label share a vertical
//!   midline, and bottom rows are anchored from `DISPLAY_HEIGHT`.
//!
//! Owner: R1-04 (spike) then R2-10 (templates). This is the R1-01 skeleton.

#![no_std]

/// The OLED bitmaps, extracted verbatim from the C++ `display/bitmaps.h`.
///
/// @generated by `tools/extract_bitmaps.py`; see that file's header comment.
pub mod bitmaps;
pub mod bitmaps_data;
pub mod display;
pub mod fmt;
pub mod font;
pub mod fullscreen;
pub mod helpers;
pub mod lang;
pub mod layout;
pub mod model;
pub mod ota;
#[cfg(feature = "scenarios")]
pub mod scenario;
pub mod system_screens;
pub mod templates;
pub mod widgets;
