#!/usr/bin/env python3
"""Extract the OLED bitmaps from `include/clevercoffee/display/bitmaps.h`.

Writes `crates/cc-display/src/bitmaps_data.rs`. The bytes are copied verbatim
from the C header, so a rendered pixel is bit-identical to the C++ one.

The three `B00011111`-style icons are kept as binary literals rather than
converted to hex, because the binary form *is* the documentation: bit 7 is the
leftmost pixel of the row, which is what `u8g2_DrawHXBMP` expects
(`u8g2_bitmap.c`: `mask = 1; ... mask <<= 1`).

    extract_bitmaps.py extract   regenerate
    extract_bitmaps.py check     fail if the generated file has drifted
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
HEADER = REPO / "include" / "clevercoffee" / "display" / "bitmaps.h"
OUT = Path(__file__).resolve().parents[1] / "src" / "bitmaps_data.rs"

# The `B...` icons, with their dimensions.
#
# The header has NO `#define ..._width/_height` for these three, unlike the hex
# bitmaps below. Their dimensions are hard-coded at each call site:
#
#   DisplayWidgets.h:84  displayWiFiStatus       -> Antenna_OK_Icon,  8, 8
#   DisplayWidgets.h:93  displayWiFiStatus       -> Antenna_NOK_Icon, 8, 8
#   DisplayWidgets.h:239 displayBluetoothStatus  -> Bluetooth_Icon,  8, 9
#
# So they are listed here, and `check` verifies the *byte count* still matches,
# which is the property that would break if someone edited the array.
ICONS = [
    ("ANTENNA_OK_ICON", "Antenna_OK_Icon", 8, 8, "radio link up"),
    ("ANTENNA_NOK_ICON", "Antenna_NOK_Icon", 8, 8, "radio link down"),
    ("BLUETOOTH_ICON", "Bluetooth_Icon", 8, 9, "Bluetooth scale connected"),
]

# The `B...` icons, then the hex ones, with their width/height from the header's
# `#define`s. Height for the `B...` icons is the byte count, because a `B...`
# array has one byte per *row* (that is the mistake the header itself makes for
# `Bluetooth_Icon`, which is 8 wide and 9 tall -- see the note below).
HEX_BITMAPS = [
    ("CLEVERCOFFEE_LOGO", "CleverCoffee_Logo", 40, 40, "the boot logo"),
    ("HEATING_LOGO", "Heating_Logo", 40, 40, "the fullscreen heating screen"),
    ("OFF_LOGO", "Off_Logo", 52, 53, "the PID-off / standby screen"),
    ("STEAM_LOGO", "Steam_Logo", 40, 40, "the steam screen"),
    ("BREW_CUP_LOGO", "Brew_Cup_Logo", 40, 40, "the brew / post-brew cup"),
    ("HOT_WATER_LOGO", "Hot_Water_Logo", 40, 40, "the hot-water fullscreen screen"),
    ("WATER_TANK_EMPTY_LOGO", "Water_Tank_Empty_Logo", 47, 64, "the water-tank-empty screen"),
    ("MANUAL_FLUSH_LOGO", "Manual_Flush_Logo", 40, 40, "the manual-flush fullscreen screen"),
]

_DEFINE = re.compile(r"^#define\s+(\w+?)_(width|height)\s+(\d+)\s*$", re.MULTILINE)
_ARRAY = re.compile(
    r"static\s+const\s+unsigned\s+char\s+(\w+)\s*\[\s*\]\s*U8X8_PROGMEM\s*=\s*\{(.*?)\}\s*;",
    re.DOTALL,
)


def parse_header(text: str) -> tuple[dict[str, int], dict[str, list[int]]]:
    dims: dict[str, int] = {}
    for name, which, value in _DEFINE.findall(text):
        dims[f"{name}_{which}"] = int(value)

    arrays: dict[str, list[int]] = {}
    for name, body in _ARRAY.findall(text):
        body = re.sub(r"//.*", "", body)
        values: list[int] = []
        for tok in body.split(","):
            tok = tok.strip()
            if not tok:
                continue
            if tok.startswith("B"):
                bits = tok[1:]
                if set(bits) - {"0", "1"}:
                    raise ValueError(f"{name}: bad binary token {tok!r}")
                if len(bits) != 8:
                    raise ValueError(f"{name}: B-token {tok!r} is not 8 bits")
                values.append(int(bits, 2))
            elif tok.startswith("0x") or tok.startswith("0X"):
                values.append(int(tok, 16))
            else:
                raise ValueError(f"{name}: unexpected token {tok!r}")
        arrays[name] = values
    return dims, arrays


def binary(v: int) -> str:
    """`0b0001_1111` for 0x1F.

    The nibble separator is `clippy::unreadable_literal`, which the workspace
    denies. The digits are otherwise exactly the C header's `B00011111`, so the
    two can still be compared by eye -- which is the point of keeping the
    binary form at all.
    """
    return f"0b{v >> 4:04b}_{v & 0xF:04b}"


HEADER_TEXT = """\
// @generated by crates/cc-display/tools/extract_bitmaps.py -- DO NOT EDIT BY HAND.
//
// Source of truth: `include/clevercoffee/display/bitmaps.h` of the C++ firmware.
// The bytes are identical -- only the C array syntax is replaced by a Rust
// `static` -- so a rendered pixel is bit-identical to the C++ one and the flash
// cost is unchanged.
//
// A `B00011111` row in the header is a *big-endian* 1bpp row: bit 7 is the
// leftmost pixel. That is exactly what `u8g2_DrawHXBMP` expects
// (`u8g2_bitmap.c`: `mask = 1; ... mask <<= 1`), so the `B...` icons are kept
// as binary literals below and the hex ones are copied as-is.
//
// NOTE on `B...` icons: the header stores one byte per ROW, not per 8 rows, so
// a `B...` icon of width 8 and height 8 has 8 bytes, and `Bluetooth_Icon` (8
// wide) has 9. `Bitmap::draw` reads them row by row, which is what
// `u8g2_DrawHXBMP` does for a 1-byte-per-row source.
//
// Regenerate with `crates/cc-display/tools/extract_bitmaps.py`.
"""


def emit(dims: dict[str, int], arrays: dict[str, list[int]]) -> str:
    parts = [HEADER_TEXT]

    for rust_name, c_name, w, h, what in ICONS:
        data = arrays[c_name]
        if len(data) != h:
            raise ValueError(
                f"{c_name}: the call sites draw it {h} rows tall, "
                f"but the array has {len(data)} bytes"
            )
        if w != 8:
            raise ValueError(
                f"{c_name}: a B... icon is one byte per row, so the width must be "
                f"8 for the bytes to be a row; the call sites draw {w}"
            )
        rows = ", ".join(binary(v) for v in data)
        parts.append(
            f"/// `{c_name}` -- `{w}x{h}`, {what}.\n"
            f"pub static {rust_name}: [u8; {len(data)}] = [{rows}];\n"
        )

    for rust_name, c_name, w, h, what in HEX_BITMAPS:
        if dims.get(f"{c_name}_width") != w or dims.get(f"{c_name}_height") != h:
            raise ValueError(
                f"{c_name}: header says {dims.get(f'{c_name}_width')}"
                f"x{dims.get(f'{c_name}_height')}, expected {w}x{h}"
            )
        data = arrays[c_name]
        stride = (w + 7) // 8
        if len(data) != stride * h:
            raise ValueError(
                f"{c_name}: {w}x{h} needs {stride * h} bytes, array has {len(data)}"
            )
        lines = [
            f"/// `{c_name}` -- `{w}x{h}`, {what}.",
            f"pub static {rust_name}: [u8; {len(data)}] = [",
        ]
        for i in range(0, len(data), stride):
            chunk = data[i: i + stride]
            lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
        lines.append("];")
        parts.append("\n".join(lines) + "\n")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mode", choices=("extract", "check"))
    args = ap.parse_args()

    dims, arrays = parse_header(HEADER.read_text(encoding="utf-8"))
    generated = emit(dims, arrays)

    if args.mode == "extract":
        OUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUT}")
        return 0

    if not OUT.is_file():
        print(f"extract_bitmaps: check FAILED: {OUT} does not exist", file=sys.stderr)
        return 1
    if OUT.read_text(encoding="utf-8") != generated:
        print(
            f"extract_bitmaps: check FAILED: {OUT} no longer matches {HEADER}.\n"
            f"                  Run: crates/cc-display/tools/extract_bitmaps.py extract",
            file=sys.stderr,
        )
        return 1
    print(f"extract_bitmaps: check OK ({OUT} matches {HEADER})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
