[package]
name = "clevercoffee-config"
description = "The parameter schema, and import and export of the config JSON."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
heapless = { workspace = true }

[dev-dependencies]

