// Parameter label translations (add more languages as needed)
const parameterLabels: Record<string, Record<string, string>> = {
  en: {
    "pid.enabled": "Enable PID Controller",
    "pid.use_ponm": "Enable PonM",
    "pid.ema_factor": "PID EMA Factor",
    "pid.regular.kp": "PID Kp",
    "pid.regular.tn": "PID Tn (=Kp/Ki)",
    "pid.regular.tv": "PID Tv (=Kd/Kp)",
    "pid.regular.i_max": "PID Integrator Max",
    "pid.steam.kp": "Steam Kp",
    "brew.setpoint": "Setpoint (°C)",
    "brew.temp_offset": "Offset (°C)",
    "steam.setpoint": "Steam Setpoint (°C)",
    STEAM_MODE: "Steam Mode",
    "standby.enabled": "Enable Standby Timer",
    "standby.time": "Standby Time",
    "display.template": "Display Template",
    "display.inverted": "Invert Display",
    "display.language": "Display Language",
    "display.fullscreen_brew_timer": "Enable Fullscreen Brew Timer",
    "display.fullscreen_manual_flush_timer":
      "Enable Fullscreen Manual Flush Timer",
    "display.fullscreen_hot_water_timer": "Enable Fullscreen Hot Water Timer",
    "display.post_brew_timer_duration": "Post Brew Timer Duration (s)",
    "display.heating_logo": "Enable Heating Logo",
    "display.pid_off_logo": "Enable 'PID Disabled' Logo",
    "mqtt.enabled": "MQTT enabled",
    "mqtt.broker": "Hostname",
    "mqtt.port": "Port",
    "mqtt.username": "Username",
    "mqtt.password": "Password",
    "mqtt.topic": "Topic Prefix",
    "mqtt.hassio.enabled": "Hass.io enabled",
    "mqtt.hassio.prefix": "Hass.io Prefix",
    "system.hostname": "Hostname",
    "system.ota_password": "OTA Password",
    "system.log_level": "Log Level",
    "system.auth.enabled": "Enable Website Authentication",
    "system.auth.username": "Website Username",
    "system.auth.password": "Website Password",
    "hardware.oled.enabled": "Enable OLED Display",
    "hardware.oled.type": "OLED Type",
    "hardware.oled.address": "I2C Address",
    "hardware.relays.heater.trigger_type": "Heater Relay Trigger Type",
    "hardware.relays.valve.trigger_type": "Valve Relay Trigger Type",
    "hardware.relays.pump.trigger_type": "Pump Relay Trigger Type",
    "hardware.switches.brew.enabled": "Enable Brew Switch",
    "hardware.switches.brew.type": "Brew Switch Type",
    "hardware.switches.brew.mode": "Brew Switch Mode",
    "hardware.switches.steam.enabled": "Enable Steam Switch",
    "hardware.switches.steam.type": "Steam Switch Type",
    "hardware.switches.steam.mode": "Steam Switch Mode",
    "hardware.switches.power.enabled": "Enable Power Switch",
    "hardware.switches.power.type": "Power Switch Type",
    "hardware.switches.power.mode": "Power Switch Mode",
    "hardware.switches.hot_water.enabled": "Enable Water Switch",
    "hardware.switches.hot_water.type": "Water Switch Type",
    "hardware.switches.hot_water.mode": "Water Switch Mode",
    "hardware.leds.status.enabled": "Enable Status LED",
    "hardware.leds.status.inverted": "Invert Status LED",
    "hardware.leds.brew.enabled": "Enable Brew LED",
    "hardware.leds.brew.inverted": "Invert Brew LED",
    "hardware.leds.steam.enabled": "Enable Steam LED",
    "hardware.leds.steam.inverted": "Invert Steam LED",
    "hardware.sensors.temperature.type": "Temperature Sensor Type",
    "hardware.sensors.pressure.enabled": "Enable Pressure Sensor",
    "hardware.sensors.watertank.enabled": "Enable Water Tank Sensor",
    "hardware.sensors.watertank.mode": "Water Tank Sensor Mode",
    "hardware.sensors.scale.enabled": "Enable Scale",
    "hardware.sensors.scale.type": "Scale Setup Type",
    "hardware.sensors.scale.samples": "Scale Samples",
    "hardware.sensors.scale.calibration": "Scale Calibration Factor",
    "hardware.sensors.scale.calibration2": "Scale Calibration Factor 2",
    "hardware.sensors.scale.known_weight": "Known Calibration Weight",
  },
  // Add other languages here, e.g. de: {...}, fr: {...}
};

export default parameterLabels;
