//! Emit the firmware's bitmaps as a C header for the display parity oracle.
//!
//! `tools/oracle/display_oracle.cpp` links the real U8g2 but must not carry its
//! own copy of the artwork: a second copy is a second thing to forget to update,
//! and the oracle would then prove that U8g2 matches a stale header. It reads
//! this output instead, so the bytes compared are the bytes the firmware ships.
//!
//!     cargo run --example emit_bitmaps --target <host> > bitmaps.h
//!
//! The C++ oracle's `BITMAPS[]` table became this list, so the mapping is
//! generated rather than transcribed.

use std::io::{self, Write};

use cc_display::bitmaps;

fn main() -> io::Result<()> {
    let out = io::stdout();
    let mut w = io::BufWriter::new(out.lock());

    writeln!(
        w,
        "// @generated by `cargo run -example emit_bitmaps`. Do not edit."
    )?;
    writeln!(w, "#pragma once")?;
    writeln!(w, "#include <U8g2lib.h>")?;

    for b in bitmaps::ALL {
        writeln!(
            w,
            "static const unsigned char {name}_bytes[{len}] = {{",
            name = b.name.to_uppercase(),
            len = b.data.len()
        )?;
        for (i, byte) in b.data.iter().enumerate() {
            write!(w, "0x{byte:02x},")?;
            if (i + 1) % 12 == 0 {
                writeln!(w)?;
            } else {
                write!(w, " ")?;
            }
        }
        writeln!(w)?;
        writeln!(w, "}};")?;
    }

    for b in bitmaps::ALL {
        writeln!(
            w,
            "static const unsigned char {name}_width = {w};",
            name = b.name.to_uppercase(),
            w = b.width
        )?;
        writeln!(
            w,
            "static const unsigned char {name}_height = {h};",
            name = b.name.to_uppercase(),
            h = b.height
        )?;
    }
    Ok(())
}
