//! The U8g2 font decoder, ported so that glyph pixels and glyph metrics agree
//! with the C++ firmware exactly.
//!
//! # Why the RLE is decoded rather than pre-rasterised
//!
//! R1-04 step 2 asks for the profont/fub atlases "converted to a Rust-embedded
//! bitmap format", and suggests `embedded-graphics`' `ImageRaw` (an
//! *uncompressed* 1bpp carrier). Measured, that is the wrong trade for this
//! firmware — see [`crate::font::data`] for the numbers and the reasoning. The
//! RLE stream is embedded byte-for-byte and the decoder below is a port of
//! `u8g2_font.c`.
//!
//! Decoding rather than storing a raster is also the only way to get *pixel
//! parity*: the glyph's x/y offset, its `glyph_width`, and the delta-x advance
//! that `getStrWidth` returns all come out of this decoder. Storing a raster
//! and measuring its bounding box instead would silently disagree with U8g2 on
//! kerning and side bearings, and the fixed-width-field layout helpers are
//! entirely built on `getStrWidth`.
//!
//! # What is ported, and from where
//!
//! | Rust | U8g2 |
//! |------|-------|
//! | [`FontInfo::read`] | `u8g2_read_font_info`, `u8g2_font.c:157` |
//! | [`BitReader`] | `u8g2_font_decode_get_unsigned_bits`, `u8g2_font.c:249` |
//! | [`Font::glyph_header`] | `u8g2_font_get_glyph_data`, `u8g2_font.c:759` |
//! | [`Glyph::decode`] | `u8g2_font_decode_glyph`, `u8g2_font.c:490` |
//! | [`Font::str_width`] | `u8g2_string_width`, `u8g2_font.c:1290` |
//! | [`Font::bbox_height`] | `u8g2_GetFontBBXHeight` + the ref-height rules, `u8g2_font.c:1189` |
//!
//! # U8g2's per-glyph `is_transparent` is NOT honoured
//!
//! U8g2 has a "transparent" font mode that skips the background runs and so
//! avoids double-drawing overlaps (`u8g2_font_decode_len`, the
//! `decode->is_transparent == 0` guard). The firmware never enables it:
//! `u8g2_SetupBuffer` hard-sets `font_decode.is_transparent = 0` (`u8g2_setup.c:93`,
//! "issue 443") and nothing in `src/` or `include/` calls `setFontMode`. This
//! port therefore always draws the background run, which is the behaviour the
//! device actually has. [`Font::decode_into`] takes the flag anyway, so a future
//! caller cannot get it wrong by accident.

use core::fmt;

/// The ten profont/fub font atlases, in U8g2's own RLE encoding.
///
/// @generated by `tools/extract_fonts.py`. The module header explains why the
/// RLE is embedded rather than expanded into an `ImageRaw` atlas, with the
/// measured per-font numbers.
pub mod data;

/// Length of the U8g2 font header, in bytes.
///
/// `u8g2_font.c:39`: `#define U8G2_FONT_DATA_STRUCT_SIZE 23`.
pub const FONT_INFO_LEN: usize = 23;

/// The U8g2 font height mode (`u8g2_font.c:1176`).
///
/// The firmware calls `setFontRefHeightExtendedText()` once, in
/// `OledDriver::prepareDisplay()`, so [`HeightMode::ExtendedText`] is what every
/// template renders under. The other two are implemented because
/// `bbox_height` — the number the whole layout is built on — depends on them,
/// and a silent mismatch here would shift every row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HeightMode {
    /// `u8g2_SetFontRefHeightText`: reference is capital A / lower g only.
    Text,
    /// `u8g2_SetFontRefHeightExtendedText`: capital A / lower g, widened to
    /// also cover the parenthesis pair.
    ExtendedText,
    /// `u8g2_SetFontRefHeightAll`: the full `max_char_height` box.
    All,
}

/// The 23-byte U8g2 font header (`u8g2_read_font_info`, `u8g2_font.c:157`).
///
/// Field names are U8g2's. `x_offset`, `y_offset`, `max_char_width`,
/// `max_char_height`, `ascent_A`, `descent_g`, `ascent_para` and `descent_para`
/// are `int8_t` in `u8g2_font_info_t` (`u8g2.h:247-256`) even though they are
/// read with `u8g2_font_get_byte`, so they are reinterpreted as signed here.
/// Getting that wrong is not cosmetic: `y_offset` is the descent, and it is
/// what makes `ref_ascent`/`ref_descent` come out right.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FontInfo {
    /// Number of glyphs in the font.
    pub glyph_cnt: u8,
    /// `0` proportional, `1` common height, `2` monospace, `3` multiple of 8.
    /// Unused by the decoder; kept so the header round-trips.
    pub bbx_mode: u8,
    /// Bits used for a background run length.
    pub bits_per_0: u8,
    /// Bits used for a foreground run length.
    pub bits_per_1: u8,
    /// Bits for `glyph_width`.
    pub bits_per_char_width: u8,
    /// Bits for `glyph_height`.
    pub bits_per_char_height: u8,
    /// Bits for the glyph's x offset.
    pub bits_per_char_x: u8,
    /// Bits for the glyph's y offset.
    pub bits_per_char_y: u8,
    /// Bits for the delta-x advance.
    pub bits_per_delta_x: u8,
    /// Widest glyph cell, in pixels.
    pub max_char_width: i8,
    /// Tallest glyph cell, in pixels. `u8g2.h:248` notes this is the *overall*
    /// height, not the ascent: `ascent = max_char_height + y_offset`.
    pub max_char_height: i8,
    /// Left side bearing.
    pub x_offset: i8,
    /// Descent, i.e. how far the box extends below the baseline.
    pub y_offset: i8,
    /// Height of capital `A`.
    pub ascent_a: i8,
    /// Depth of lower `g`.
    pub descent_g: i8,
    /// Height of `(`.
    pub ascent_para: i8,
    /// Depth of `)`.
    pub descent_para: i8,
    /// Byte offset of the first `A` in the glyph table.
    pub start_pos_upper_a: u16,
    /// Byte offset of the first `a` in the glyph table.
    pub start_pos_lower_a: u16,
    /// Byte offset of the Unicode section's index table.
    pub start_pos_unicode: u16,
}

#[inline]
fn get_byte(font: &[u8], offset: usize) -> u8 {
    font[offset]
}

#[inline]
fn get_word(font: &[u8], offset: usize) -> u16 {
    u16::from(font[offset]) << 8 | u16::from(font[offset + 1])
}

/// Reinterpret a header byte as the `int8_t` U8g2's struct declares it
/// (`u8g2.h:247-256`).
#[inline]
fn as_i8(v: u8) -> i8 {
    // Wrapping, not truncating: the conversion is a reinterpretation, and the
    // alternative (`i8::try_from` + clamp) would silently turn `y_offset` 254
    // into 127 and move every row.
    #[allow(
        clippy::cast_possible_wrap,
        reason = "reinterpreting u8 as i8 is the intent; u8g2.h:247-256 declares these fields int8_t"
    )]
    let out = v as i8;
    out
}

impl FontInfo {
    /// Parse the 23-byte header.
    ///
    /// # Panics
    ///
    /// If `font` is shorter than [`FONT_INFO_LEN`]. Every font in
    /// [`data`] is far longer, and the only way to get here with a short slice
    /// is to hand `Font::new` a hand-built array.
    #[must_use]
    pub fn read(font: &[u8]) -> Self {
        assert!(
            font.len() >= FONT_INFO_LEN,
            "U8g2 font is shorter than its {FONT_INFO_LEN}-byte header"
        );
        Self {
            glyph_cnt: get_byte(font, 0),
            bbx_mode: get_byte(font, 1),
            bits_per_0: get_byte(font, 2),
            bits_per_1: get_byte(font, 3),
            bits_per_char_width: get_byte(font, 4),
            bits_per_char_height: get_byte(font, 5),
            bits_per_char_x: get_byte(font, 6),
            bits_per_char_y: get_byte(font, 7),
            bits_per_delta_x: get_byte(font, 8),
            max_char_width: as_i8(get_byte(font, 9)),
            max_char_height: as_i8(get_byte(font, 10)),
            x_offset: as_i8(get_byte(font, 11)),
            y_offset: as_i8(get_byte(font, 12)),
            ascent_a: as_i8(get_byte(font, 13)),
            descent_g: as_i8(get_byte(font, 14)),
            ascent_para: as_i8(get_byte(font, 15)),
            descent_para: as_i8(get_byte(font, 16)),
            start_pos_upper_a: get_word(font, 17),
            start_pos_lower_a: get_word(font, 19),
            start_pos_unicode: get_word(font, 21),
        }
    }
}

/// U8g2's LSB-first bit cursor over the glyph stream
/// (`u8g2_font_decode_t` + `u8g2_font_decode_get_unsigned_bits`,
/// `u8g2_font.c:249`).
///
/// U8g2 reads bits LSB-first within each byte and advances the byte pointer
/// when a read straddles a byte boundary. The signed variant subtracts the
/// midpoint (`u8g2_font_decode_get_signed_bits`, `u8g2_font.c:288`).
#[derive(Clone, Copy, Debug)]
pub struct BitReader<'a> {
    data: &'a [u8],
    pos: usize,
    bit_pos: u8,
}

impl<'a> BitReader<'a> {
    /// Start reading at `offset` into `data`.
    #[must_use]
    pub fn new(data: &'a [u8], offset: usize) -> Self {
        Self {
            data,
            pos: offset,
            bit_pos: 0,
        }
    }

    /// Current byte offset. U8g2 exposes this as `decode_ptr`.
    #[must_use]
    pub fn offset(&self) -> usize {
        self.pos
    }

    /// Read `cnt` bits, unsigned.
    ///
    /// # Panics
    ///
    /// If the read runs past `data`. A well-formed font cannot do this: the
    /// terminator is a zero run followed by a `0` bit, so the decoder stops
    /// before the end.
    #[must_use]
    pub fn unsigned(&mut self, cnt: u8) -> u8 {
        assert!(cnt <= 8, "U8g2 never reads more than 8 bits at a time");
        // Widened to u16 for the straddle shift: when `bit_pos == 0` the shift
        // is by 8, which is fine in C (the u8 is promoted to int) but is an
        // overflow on a Rust `u8`.
        let mut val = u16::from(self.data[self.pos] >> self.bit_pos);
        let mut total = self.bit_pos + cnt;
        if total >= 8 {
            self.pos += 1;
            val |= u16::from(self.data[self.pos]) << (8 - self.bit_pos);
            total -= 8;
        }
        self.bit_pos = total;
        u8::try_from(val & ((1u16 << cnt) - 1)).unwrap_or(0)
    }

    /// Read `cnt` bits, two's-complement signed.
    #[must_use]
    pub fn signed(&mut self, cnt: u8) -> i8 {
        let v = i16::from(self.unsigned(cnt));
        // `1 << (cnt - 1)` as the midpoint. `unsigned` is masked, so `cnt` is
        // never 0 in practice; guard anyway rather than panic.
        let mid = if cnt == 0 { 0 } else { 1i16 << (cnt - 1) };
        // The result always fits in i8: the unsigned read was masked to `cnt`
        // bits and `cnt <= 8`.
        i8::try_from(v - mid).unwrap_or(0)
    }
}

/// The three header fields every run-length walk needs
/// (`u8g2_font_setup_decode`, `u8g2_font.c:441`).
#[derive(Clone, Copy, Debug)]
pub struct GlyphHeader {
    /// Offset of the glyph's own data (past the encoding and length bytes).
    pub data: usize,
    /// Bounding-box width in pixels. `0` means "no ink" (a space).
    pub width: u8,
    /// Bounding-box height in pixels.
    pub height: u8,
    /// Left side bearing of the ink.
    pub x_offset: i8,
    /// Vertical offset of the ink; the baseline sits at `-y_offset` from the
    /// top of the box.
    pub y_offset: i8,
    /// Advance in x, i.e. the delta-x the pen moves by.
    pub delta_x: i8,
}

/// A U8g2 font: the raw RLE stream, plus its parsed header.
///
/// The header is derived on each `info()` call rather than cached, because
/// [`Font`] must stay `Copy` and small: a display context holds one per font and
/// is copied by value into every widget. The parse is 23 byte loads.
#[derive(Clone, Copy)]
pub struct Font {
    data: &'static [u8],
}

impl fmt::Debug for Font {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let i = FontInfo::read(self.data);
        f.debug_struct("Font")
            .field("len", &self.data.len())
            .field("max_char_width", &i.max_char_width)
            .field("max_char_height", &i.max_char_height)
            .field("ascent_a", &i.ascent_a)
            .field("descent_g", &i.descent_g)
            .finish()
    }
}

impl Font {
    /// Wrap a font's raw bytes.
    ///
    /// # Panics
    ///
    /// If `data` is shorter than [`FONT_INFO_LEN`]. Every font in [`data`] is
    /// far longer, so this only fires on a hand-built array.
    #[must_use]
    pub fn new(data: &'static [u8]) -> Self {
        assert!(
            data.len() >= FONT_INFO_LEN,
            "U8g2 font is shorter than its 23-byte header"
        );
        Self { data }
    }

    /// The parsed 23-byte header.
    #[must_use]
    pub fn info(&self) -> FontInfo {
        FontInfo::read(self.data)
    }

    /// The raw RLE stream.
    #[must_use]
    pub const fn raw(&self) -> &'static [u8] {
        self.data
    }

    /// Find a glyph by encoding.
    ///
    /// Port of `u8g2_font_get_glyph_data` (`u8g2_font.c:759`). `None` means the
    /// font has no such glyph, and U8g2 then advances the pen by zero and draws
    /// nothing — which is how a missing `°` in `fub20` behaves.
    ///
    /// Note U8g2's *linear* search, and its three-way start: `>= 'a'` jumps
    /// straight to the lowercase block, `>= 'A'` to the uppercase one, and
    /// anything below `'A'` (space, digits, punctuation) starts at the top.
    #[must_use]
    pub fn glyph_header(&self, encoding: u16) -> Option<GlyphHeader> {
        let info = self.info();
        let mut font = FONT_INFO_LEN;

        if encoding <= 255 {
            let e = u8::try_from(encoding).unwrap_or(0);
            if e >= b'a' {
                font += usize::from(info.start_pos_lower_a);
            } else if e >= b'A' {
                font += usize::from(info.start_pos_upper_a);
            }

            loop {
                let cur = get_byte(self.data, font);
                let len = get_byte(self.data, font + 1);
                if len == 0 {
                    break;
                }
                if cur == e {
                    return Some(self.read_glyph_header(font + 2));
                }
                font += usize::from(len);
            }
        } else {
            font += usize::from(info.start_pos_unicode);
            let mut table = font;
            // The Unicode index table is a list of (offset, max_encoding)
            // pairs; walk it to the first entry that can cover `encoding`.
            loop {
                let step = get_word(self.data, table);
                let entry_max = get_word(self.data, table + 2);
                table += 4;
                if entry_max >= encoding {
                    break;
                }
                font += usize::from(step);
            }

            loop {
                let e = get_word(self.data, font);
                if e == 0 {
                    break;
                }
                if e == encoding {
                    return Some(self.read_glyph_header(font + 3));
                }
                font += usize::from(get_byte(self.data, font + 2));
            }
        }

        None
    }

    /// Read the per-glyph header at `data` (width, height, offsets, advance).
    ///
    /// `u8g2_font_setup_decode` + the first three reads of
    /// `u8g2_font_decode_glyph`.
    fn read_glyph_header(&self, data: usize) -> GlyphHeader {
        let info = self.info();
        let mut r = BitReader::new(self.data, data);
        let width = r.unsigned(info.bits_per_char_width);
        let height = r.unsigned(info.bits_per_char_height);
        let x_offset = r.signed(info.bits_per_char_x);
        let y_offset = r.signed(info.bits_per_char_y);
        let delta_x = r.signed(info.bits_per_delta_x);
        GlyphHeader {
            data,
            width,
            height,
            x_offset,
            y_offset,
            delta_x,
        }
    }

    /// Decode a glyph's runs into `sink`, in pen-relative coordinates.
    ///
    /// `sink` is called as `sink(x, y, len, foreground)` for each run of `len`
    /// pixels starting at `(x, y)`, where `(0, 0)` is the pen position and `y`
    /// grows downward. `x` and `y` are the *ink* origin, i.e. the caller has
    /// already applied the glyph's `x_offset` and `-(height + y_offset)`.
    ///
    /// Both foreground and background runs are reported, in stream order,
    /// because U8g2 paints both: the firmware is in non-transparent mode, so a
    /// glyph erases the background of its own box before drawing its ink. The
    /// caller picks the colour from the flag.
    ///
    /// A glyph with `width == 0` — a space — produces no calls, which is
    /// exactly U8g2's `if (decode->glyph_width > 0)` guard.
    ///
    /// # Panics
    ///
    /// Never, for a well-formed glyph; the run-length stream is self-
    /// terminating (`u8g2_font.c:695-700`).
    pub fn decode_into<F: FnMut(i16, i16, u8, bool)>(&self, header: &GlyphHeader, mut sink: F) {
        if header.width == 0 {
            return;
        }
        let info = self.info();
        let mut r = BitReader::new(self.data, header.data);
        // Re-read the header bits: the RLE stream is a single cursor, so the
        // run-length walk has to start from the beginning of the glyph.
        let _ = r.unsigned(info.bits_per_char_width);
        let _ = r.unsigned(info.bits_per_char_height);
        let _ = r.signed(info.bits_per_char_x);
        let _ = r.signed(info.bits_per_char_y);
        let _ = r.signed(info.bits_per_delta_x);

        let mut lx: i16 = 0;
        let mut ly: i16 = 0;
        let h = i16::from(header.height);

        loop {
            let a = r.unsigned(info.bits_per_0);
            let b = r.unsigned(info.bits_per_1);
            loop {
                decode_len(&mut lx, &mut ly, a, false, header.width, &mut sink);
                decode_len(&mut lx, &mut ly, b, true, header.width, &mut sink);
                if r.unsigned(1) == 0 {
                    break;
                }
            }
            if ly >= h {
                break;
            }
        }
    }

    /// Width of `text` in pixels, matching U8g2's `getStrWidth`.
    ///
    /// Port of `u8g2_string_width` (`u8g2_font.c:1290`). Two details in that
    /// function are load-bearing and are reproduced rather than "fixed":
    ///
    /// * the last glyph is measured with its *ink width* rather than its
    ///   advance, plus its x offset, so a proportional font's trailing
    ///   side-bearing is excluded (U8g2's "issue #16" and "#46" comments); and
    /// * an unknown glyph contributes 0 and terminates nothing.
    ///
    /// The 23-byte `&str` is read as Latin-1, which is what
    /// `u8x8_ascii_next` does for `drawStr`/`getStrWidth`. For the UTF-8 entry
    /// points see [`Font::str_width_utf8`].
    #[must_use]
    pub fn str_width(&self, text: &str) -> i32 {
        self.str_width_impl(text.chars().map(latin1_of))
    }

    /// Width of a UTF-8 `text`, matching U8g2's `getUTF8Width`.
    ///
    /// Width in pixels, looking each `char` up as itself.
    ///
    /// Same arithmetic as [`Font::str_width`]; the difference is only that a
    /// non-Latin code point is looked up as itself rather than being folded to
    /// `0xFFFF`. Both end at the same result for the ten embedded fonts, since
    /// they carry no glyph above U+00FF. `displayWrappedMessage` uses this.
    #[must_use]
    pub fn str_width_utf8(&self, text: &str) -> i32 {
        self.str_width_impl(text.chars().map(code_point_of))
    }

    /// The `u8g2_GetGlyphWidth` loop, over an iterator of decoded code points.
    ///
    /// This is `u8g2_string_width` (`u8g2_font.c:1325`) verbatim, including
    /// both of its quirks, because both are pixel-affecting:
    ///
    /// 1. **The last glyph is measured differently.** After summing every
    ///    glyph's advance, U8g2 subtracts the last advance and adds that
    ///    glyph's *ink* width plus its x-offset. For a proportional font the
    ///    advance usually exceeds the ink width by the inter-glyph gap, so this
    ///    is how U8g2 measures a string as tightly as its last glyph.
    /// 2. **The first glyph's x-offset is added back** (issue
    ///    [#1561](https://github.com/olikraus/u8g2/issues/1561)), enabled by
    ///    `U8G2_BALANCED_STR_WIDTH_CALCULATION`, which `u8g2.h:174` defines
    ///    *unless* `U8G2_NO_BALANCED_STR_WIDTH_CALCULATION` is set. Dropping
    ///    it makes every string whose first glyph is inset -- `'!'`, `'('`,
    ///    `'i'`, `'"'` in `profont10` -- one or two pixels narrow, which moves
    ///    a right-aligned or centred label and shows up in the goldens.
    ///
    /// Both terms are skipped when the last glyph has zero ink width, which is
    /// U8g2's guard for a trailing space (issue
    /// [#16](https://github.com/olikraus/u8g2/issues/16)).
    fn str_width_impl<I: Iterator<Item = u16>>(&self, codes: I) -> i32 {
        /// U8g2's sentinel for "no first glyph seen yet". Any real x-offset is
        /// in -128..=127, so -64 cannot collide with one.
        const UNSET: i32 = -64;

        let mut w: i32 = 0;
        let mut last_delta: i32 = 0;
        let mut last_width: u8 = 0;
        let mut last_x_offset: i8 = 0;
        let mut initial_x_offset: i32 = UNSET;

        for e in codes {
            if e == 0xffff {
                break;
            }
            if e == 0xfffe {
                continue;
            }
            let Some(header) = self.glyph_header(e) else {
                // `u8g2_GetGlyphWidth` returns 0 for a missing glyph and leaves
                // `glyph_width` alone, so the trailing adjustment is skipped
                // when a *missing* glyph is last.
                last_delta = 0;
                last_width = 0;
                continue;
            };
            last_delta = i32::from(header.delta_x);
            last_width = header.width;
            last_x_offset = header.x_offset;
            if initial_x_offset == UNSET {
                initial_x_offset = i32::from(header.x_offset);
            }
            w += last_delta;
        }

        if last_width != 0 {
            w -= last_delta;
            w += i32::from(last_width);
            w += i32::from(last_x_offset);
            if initial_x_offset > 0 {
                w += initial_x_offset;
            }
        }
        w
    }

    /// `ref_ascent + ref_descent` under `mode` — U8g2's *reference* box.
    ///
    /// Ported from `u8g2_UpdateRefHeight` (`u8g2_font.c:1189`). Note the
    /// asymmetry U8g2 uses for [`HeightMode::All`]: it takes the ascent from
    /// `max_char_height + y_offset` and the descent from `y_offset`, so the
    /// modes genuinely disagree.
    ///
    /// This is **not** the ink height and **not** the row height the Modern
    /// template uses. See [`Font::ink_box`] and
    /// [`crate::templates::modern_layout`].
    #[must_use]
    pub fn ref_box_height(&self, mode: HeightMode) -> i32 {
        let (a, d) = self.ref_height(mode);
        i32::from(a) + i32::from(d)
    }

    /// `(ref_ascent, ref_descent)` under `mode`.
    ///
    /// The y coordinate a `setFontPosTop` `drawStr` places the *reference*
    /// ascent's top at is `y + ref_ascent + 1` — the `+1` is U8g2's
    /// `u8g2_font_calc_vref_top` (`u8g2_font.c:1237`), which deliberately puts
    /// the reference one pixel above the glyph box.
    #[must_use]
    pub fn ref_height(&self, mode: HeightMode) -> (i8, i8) {
        let i = self.info();
        let mut ascent = i.ascent_a;
        let mut descent = i.descent_g;
        match mode {
            HeightMode::Text => {}
            HeightMode::ExtendedText => {
                if ascent < i.ascent_para {
                    ascent = i.ascent_para;
                }
                if descent > i.descent_para {
                    descent = i.descent_para;
                }
            }
            HeightMode::All => {
                let full = i.max_char_height.saturating_add(i.y_offset);
                if ascent < full {
                    ascent = full;
                }
                if descent > i.y_offset {
                    descent = i.y_offset;
                }
            }
        }
        (ascent, descent)
    }

    /// `u8g2_GetMaxCharHeight` — the raw `max_char_height` byte.
    ///
    /// This is *not* the row height; `DisplayWidgets::displayWrappedMessage`
    /// uses it as a line height, and it is deliberately the other number. Kept
    /// separate from [`Font::ref_box_height`] so the two cannot be confused.
    #[must_use]
    pub fn max_char_height(&self) -> i32 {
        i32::from(self.info().max_char_height)
    }

    /// The tight pixel box `text` will ink, given a `setFontPosTop` origin.
    ///
    /// This is what an executable "does it fit?" check must use, because it is
    /// what actually reaches the framebuffer. It is measured by running the
    /// decoder, not read from the header, since a font's ink for a given string
    /// depends on which glyphs are present and on each glyph's own y offset.
    ///
    /// Returns `(min_x, min_y, max_x, max_y)` **relative to the pen**, with
    /// `max_*` inclusive. `(0, 0, -1, -1)` means the string inks nothing (a
    /// blank line, or a string of spaces).
    ///
    /// # Panics
    ///
    /// Never, for valid Latin-1 input.
    #[must_use]
    pub fn ink_box(&self, text: &str) -> (i32, i32, i32, i32) {
        let info = self.info();
        // `setFontPosTop` puts the reference ascent's top at `pen_y +
        // ref_ascent + 1`; from there a glyph's ink top is `-h - y_offset`
        // below that (u8g2_font.c:512, `target_y -= h + y`).
        let (_, ref_descent) = self.ref_height(HeightMode::ExtendedText);
        let vref = i32::from(info.ascent_a.max(info.ascent_para)) + 1;
        let _ = ref_descent;

        let mut min_x = i32::MAX;
        let mut min_y = i32::MAX;
        let mut max_x = i32::MIN;
        let mut max_y = i32::MIN;
        let mut pen_x = 0i32;

        for &byte in text.as_bytes() {
            if byte == 0 || byte == b'\n' {
                break;
            }
            let Some(header) = self.glyph_header(u16::from(byte)) else {
                continue;
            };
            if header.width > 0 {
                let top = vref - i32::from(header.height) - i32::from(header.y_offset);
                let left = pen_x + i32::from(header.x_offset);
                let right = left + i32::from(header.width) - 1;
                let bottom = top + i32::from(header.height) - 1;
                min_x = min_x.min(left);
                min_y = min_y.min(top);
                max_x = max_x.max(right);
                max_y = max_y.max(bottom);
            }
            pen_x += i32::from(header.delta_x);
        }

        if min_x > max_x {
            (0, 0, -1, -1)
        } else {
            (min_x, min_y, max_x, max_y)
        }
    }
}

/// Walk one run-length, wrapping at the glyph's right edge.
///
/// `u8g2_font_decode_len` (`u8g2_font.c:344`). The glyph is stored as a
/// sequence of horizontal runs that are `glyph_width` wide; a run longer than
/// the remaining row spills into the next. Background and foreground runs are
/// both reported — U8g2 paints both, since the firmware is in non-transparent
/// mode.
fn decode_len<F: FnMut(i16, i16, u8, bool)>(
    lx: &mut i16,
    ly: &mut i16,
    len: u8,
    is_foreground: bool,
    glyph_width: u8,
    sink: &mut F,
) {
    let mut cnt = i16::from(len);
    loop {
        let rem = i16::from(glyph_width) - *lx;
        let current = if cnt < rem { cnt } else { rem };
        if current > 0 {
            sink(*lx, *ly, u8::try_from(current).unwrap_or(0), is_foreground);
        }
        if cnt < rem {
            break;
        }
        cnt -= rem;
        *lx = 0;
        *ly += 1;
    }
    *lx += cnt;
}

// ---------------------------------------------------------------- the fonts

/// `u8g2_font_profont10_tf` — 10 px, the Modern setpoint label / brew footer.
#[must_use]
pub fn profont10() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT10_TF)
}

/// `u8g2_font_profont11_tf` — 11 px, the status bar and most field labels.
#[must_use]
pub fn profont11() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT11_TF)
}

/// `u8g2_font_profont12_tf` — 12 px, the backflush system screen.
#[must_use]
pub fn profont12() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT12_TF)
}

/// `u8g2_font_profont15_tf` — 15 px, the hot-water timer unit.
#[must_use]
pub fn profont15() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT15_TF)
}

/// `u8g2_font_profont17_tf` — 17 px, the Modern degree sign and brew fields.
#[must_use]
pub fn profont17() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT17_TF)
}

/// `u8g2_font_profont22_tf` — 22 px, the Upright / fullscreen brew digits.
#[must_use]
pub fn profont22() -> Font {
    Font::new(&data::U8G2_FONT_PROFONT22_TF)
}

/// `fub17` — the "fub" (thick) face at 17 px, the backflush title.
#[must_use]
pub fn fub17() -> Font {
    Font::new(&data::U8G2_FONT_FUB17_TF)
}

/// `u8g2_font_fub20_tf` — 20 px, the Modern idle temperature and Upright status.
#[must_use]
pub fn fub20() -> Font {
    Font::new(&data::U8G2_FONT_FUB20_TF)
}

/// `u8g2_font_fub25_tf` — 25 px, the fullscreen brew timer and heating logo.
#[must_use]
pub fn fub25() -> Font {
    Font::new(&data::U8G2_FONT_FUB25_TF)
}

/// `u8g2_font_fub30_tf` — 30 px, the temperature-only template's big readout.
#[must_use]
pub fn fub30() -> Font {
    Font::new(&data::U8G2_FONT_FUB30_TF)
}

/// The Latin-1 code point a `char` stands for.
///
/// U8g2's ASCII entry points walk a string a *byte* at a time
/// (`u8x8_ascii_next`, `u8g2_font.c:1467`) and the firmware's strings are
/// Latin-1: the degree sign is `static_cast<char>(176)`, one `0xB0` byte.
///
/// A Rust `&str` cannot hold a lone `0xB0` -- it is not valid UTF-8 -- so
/// `"\u{b0}"` is *two* bytes, and a byte walk would look up `0xC2` then `0xB0`
/// and measure 30 px instead of the measured 25 px in `profont10`. Folding the
/// code point back to a single value makes the two agree on every string the
/// firmware draws (ASCII, plus that one byte).
#[must_use]
pub(crate) fn latin1_of(c: char) -> u16 {
    let v = c as u32;
    if v <= 0xff {
        #[allow(
            clippy::cast_possible_truncation,
            reason = "the value is checked to be <= 0xFF above"
        )]
        return v as u16;
    }
    0xffff
}

/// A `char` as the code point to look up in a font.
///
/// Used by the UTF-8 entry points, where a code point above Latin-1 is looked up
/// as itself. None of the ten embedded fonts carry such a glyph, so the result
/// is a missing glyph either way; the distinction is kept so the arithmetic
/// matches U8g2's for a font that did.
#[must_use]
pub(crate) fn code_point_of(c: char) -> u16 {
    let v = c as u32;
    if v <= 0xffff {
        #[allow(
            clippy::cast_possible_truncation,
            reason = "the value is checked to be <= 0xFFFF above"
        )]
        return v as u16;
    }
    0xffff
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One of the ten fonts, named.
    type NamedFont = (&'static str, fn() -> Font);

    /// The ten fonts the templates use, so a parametrised check covers all.
    const ALL: [NamedFont; 10] = [
        ("profont10", profont10),
        ("profont11", profont11),
        ("profont12", profont12),
        ("profont15", profont15),
        ("profont17", profont17),
        ("profont22", profont22),
        ("fub17", fub17),
        ("fub20", fub20),
        ("fub25", fub25),
        ("fub30", fub30),
    ];

    #[test]
    fn every_font_has_a_plausible_header() {
        for (name, make) in ALL {
            let f = make();
            let i = f.info();
            assert!(i.glyph_cnt > 0, "{name}: glyph_cnt is 0");
            assert!(
                i.max_char_width > 0,
                "{name}: max_char_width is not positive"
            );
            assert!(
                i.max_char_height > 0,
                "{name}: max_char_height is not positive"
            );
            // The RLE field widths must be sane or the decoder reads garbage.
            for (field, v) in [
                ("bits_per_0", i.bits_per_0),
                ("bits_per_1", i.bits_per_1),
                ("bits_per_char_width", i.bits_per_char_width),
                ("bits_per_char_height", i.bits_per_char_height),
                ("bits_per_char_x", i.bits_per_char_x),
                ("bits_per_char_y", i.bits_per_char_y),
                ("bits_per_delta_x", i.bits_per_delta_x),
            ] {
                assert!((1..=8).contains(&v), "{name}: {field} = {v}, outside 1..=8");
            }
        }
    }

    #[test]
    fn glyph_walk_stays_inside_the_font() {
        // A mis-parsed header makes the linear glyph-table walk run off the
        // end, so this catches the whole `start_pos_*` mechanism.
        for (name, make) in ALL {
            let f = make();
            for e in 0u16..=255 {
                if let Some(h) = f.glyph_header(e) {
                    assert!(
                        h.data < f.raw().len(),
                        "{name}: glyph {e} points past the end"
                    );
                }
            }
        }
    }

    #[test]
    fn digits_are_monotonic_in_advance() {
        // Not a U8g2 invariant, but a cheap smoke test that the delta-x field
        // is being read: a font where every digit had the same advance would
        // mean `bits_per_delta_x` or the glyph offsets are wrong.
        for (name, make) in ALL {
            let f = make();
            let zero = f.glyph_header(u16::from(b'0')).expect("digit 0");
            let one = f.glyph_header(u16::from(b'1')).expect("digit 1");
            assert!(
                zero.delta_x > 0 && one.delta_x > 0,
                "{name}: digit advance is not positive"
            );
        }
    }

    #[test]
    fn string_width_is_the_sum_of_advances_minus_the_last_side_bearing() {
        // Reproduce U8g2's own arithmetic on a case we can check by hand from
        // the header, rather than trusting a golden number nobody derived.
        let f = profont11();
        let zero = f.glyph_header(u16::from(b'0')).unwrap();
        let text = "000";
        let by_advances = 3 * i32::from(zero.delta_x);
        assert_eq!(
            f.str_width(text),
            by_advances - i32::from(zero.delta_x)
                + i32::from(zero.width)
                + i32::from(zero.x_offset)
        );
    }

    #[test]
    fn width_is_additive_across_a_repeated_glyph() {
        // "N x" is (N-1) advances plus the last glyph's ink, so adding one more
        // character adds exactly one advance. This is the property the
        // fixed-width-field helpers depend on.
        let f = fub20();
        let one = f.str_width("8");
        let two = f.str_width("88");
        let three = f.str_width("888");
        let advance = i32::from(f.glyph_header(u16::from(b'8')).unwrap().delta_x);
        assert_eq!(two - one, advance);
        assert_eq!(three - two, advance);
    }

    #[test]
    fn ref_box_heights_match_the_cpp_probe() {
        // Measured from the real U8g2 (see the `ref_heights` table in this
        // module's docs and `crates/cc-display/tests/parity.rs`): with
        // `setFontRefHeightExtendedText()`, `getFontAscent()` and
        // `getFontDescent()` return these. The C++ templates never read them
        // directly, but they determine where ink lands under `setFontPosTop()`,
        // so a drift here moves every glyph.
        assert_eq!((fub20().ref_height(HeightMode::ExtendedText)), (20, -5));
        assert_eq!((profont17().ref_height(HeightMode::ExtendedText)), (13, -3));
        assert_eq!((profont11().ref_height(HeightMode::ExtendedText)), (8, -2));
        assert_eq!((profont10().ref_height(HeightMode::ExtendedText)), (7, -2));
        assert_eq!((fub30().ref_height(HeightMode::ExtendedText)), (31, -7));
    }

    #[test]
    fn ink_box_matches_the_cpp_measured_ink() {
        // Oracle numbers: draw at y=20, read the framebuffer, report the ink
        // extent. `tools/display_oracle.cpp` reproduces this.
        //
        //   fub20   "100.0" -> y=21..40  (20 rows)
        //   fub20   "Ay"    -> y=21..45  (25 rows, descender of y)
        //   profont17 "Ay"  -> y=23..36  (14 rows)
        let (_, top, _, bottom) = fub20().ink_box("100.0");
        assert_eq!((top + 20, bottom + 20), (21, 40));

        let (_, top, _, bottom) = fub20().ink_box("Ay");
        assert_eq!((top + 20, bottom + 20), (21, 45));

        let (_, top, _, bottom) = profont17().ink_box("Ay");
        assert_eq!((top + 20, bottom + 20), (23, 36));
    }

    #[test]
    fn a_blank_string_has_no_ink_box() {
        assert_eq!(fub20().ink_box("   "), (0, 0, -1, -1));
        assert_eq!(fub20().ink_box(""), (0, 0, -1, -1));
    }

    #[test]
    fn space_has_no_ink_but_still_advances() {
        let f = profont11();
        let sp = f.glyph_header(u16::from(b' ')).expect("space");
        assert_eq!(sp.width, 0, "space should have zero ink width");
        assert!(sp.delta_x > 0, "space should still advance the pen");
        assert_eq!(f.str_width(" "), i32::from(sp.delta_x));
    }

    #[test]
    fn a_missing_glyph_contributes_nothing() {
        // fub fonts have no degree sign in some builds; a missing glyph must
        // not panic and must not add width.
        let f = fub20();
        let w = f.str_width("\u{fffd}");
        assert!(w >= 0);
    }

    #[test]
    fn bit_reader_reads_lsb_first() {
        // U8g2 reads bits LSB-first within a byte, straddling byte boundaries.
        // The bytes are `0b1011_0101`, `0b0000_1110`, `0b0000_0000`.
        //
        //   read 3 -> 0b101 = 5, no straddle
        //   read 5 -> 0b1011_0101 >> 3 = 0b1_0110, & 0b1_1111 = 0b1_0110
        //   read 8 -> straddle (bit_pos 0 + 8 >= 8): the high part contributes
        //             nothing, so this is byte[1] = 0b0000_1110
        let bytes = [0b1011_0101u8, 0b0000_1110u8, 0b0000_0000u8];
        let mut r = BitReader::new(&bytes, 0);
        assert_eq!(r.unsigned(3), 0b101);
        assert_eq!(r.unsigned(5), 0b1_0110);
        assert_eq!(r.unsigned(8), 0b0000_1110);
        assert_eq!(r.offset(), 2);
    }

    #[test]
    fn an_eight_bit_read_always_consumes_a_ninth_byte() {
        // Reproduced deliberately, not as an oversight. U8g2's
        // `u8g2_font_decode_get_unsigned_bits` advances `decode_ptr` and reads
        // the next byte whenever `bit_pos + cnt >= 8` — which is *also* true
        // for `bit_pos == 0, cnt == 8`, where the extra byte contributes
        // nothing because the result is masked to 8 bits. Every U8g2 font
        // therefore has one padding byte after the last field read at a byte
        // boundary, and the embedded arrays are sized for it.
        //
        // This port keeps the behaviour, so its slice bounds match U8g2's and a
        // read that runs off the end is a genuine font defect rather than a
        // silently-different result.
        let bytes = [0b1111_1111u8, 0b1010_1010u8];
        let mut r = BitReader::new(&bytes, 0);
        assert_eq!(r.unsigned(8), 0b1111_1111);
        assert_eq!(
            r.offset(),
            1,
            "the pointer advanced even though nothing was needed"
        );
    }

    #[test]
    fn signed_reads_are_offset_binary() {
        // `u8g2_font_decode_get_signed_bits` subtracts the midpoint
        // `1 << (cnt-1)`. So a `cnt`-bit field reads as
        // `value - 2^(cnt-1)`, i.e. OFFSET BINARY, not two's complement: the
        // all-zero pattern is `-2^(cnt-1)`, and the midpoint pattern
        // (top bit set, rest clear) is zero.
        //
        // Two 4-bit reads need two bytes: the second straddles.
        let bytes = [0b0000_1000u8, 0b0000_0000u8];
        let mut r = BitReader::new(&bytes, 0);
        assert_eq!(r.signed(4), 0, "0b1000 is the midpoint, so 0");
        assert_eq!(r.signed(4), -8, "0b0000 is the minimum, so -8");
    }
}
