#!/usr/bin/env python3
"""Every lint this workspace names must be a lint that EXISTS somewhere.

Why this is needed at all
-------------------------
`Cargo.toml` sets `unknown_lints = "allow"`. That is not sloppiness: this
repository runs clippy on two generations at once (`rust.yml`'s host job on the
runner's `stable`, the device job on the Espressif `esp` 1.97 fork), every recipe
passes `-D warnings`, and `unknown_lints` is warn-by-default -- so before that
setting, one suppression naming a lint a given channel predates took the whole
build down:

    error: unknown lint: `clippy::assert_is_empty`
       = note: `-D unknown-lints` implied by `-D warnings`

That is what broke PR #96. The allowance is the correct fix for the *symptom*;
this script is the fix for the *risk the allowance creates*, which is that a
misspelled or hallucinated lint name in an `allow` would silently do nothing.

The rule
--------
    exists on BOTH channels  -> fine, and it is doing work everywhere
    exists on ONE            -> fine, and REPORTED: that is the half of the
                                two-channel surface, and worth knowing about
    exists on NEITHER        -> ERROR: a typo, or a lint that never existed

Channels
--------
`CC_LINT_CHANNELS`, colon separated, default `stable:esp`. Each must be
installed (`rustup toolchain list`). A channel that is missing is a hard error,
not a skip: a channel that cannot be probed is a channel nobody is protecting.

Exit codes: 0 = clean, 1 = a name exists on neither channel, 2 = bad invocation.
"""

from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

# `#[allow(...)]`, `#[expect(...)]`, `#![allow(...)]`, `#![expect(...)]`.
# The body is read to its matching `)]`, so a `reason = "..."` containing brackets
# does not truncate it.
ATTR = re.compile(r"#!?\[\s*(?:allow|expect)\(")
LINT = re.compile(r"\b(clippy::[a-z_]+)\b")
RUST_LINT = re.compile(r"\b(unknown_lints|unsafe_code|missing_docs|dead_code)\b")

PROBE_CRATE = """\
// Generated by scripts/lint-names.py. Every lint this workspace names, in one
// attribute, so clippy reports each name it does not know in a single run.
#![allow({names})]
pub fn probe() {{}}
"""

SKIP_DIRS = {"target", ".embuild", "__pycache__", "node_modules", ".git"}


def collect(root: pathlib.Path) -> set[str]:
    names: set[str] = set()
    files = [root / "Cargo.toml", *root.glob("crates/**/*.rs"), *root.glob("scripts/*.py")]
    for path in files:
        if not path.is_file() or any(p in SKIP_DIRS for p in path.parts):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in ATTR.finditer(text):
            # Walk forward balancing parentheses from the match.
            i, depth = m.end() - 1, 0
            while i < len(text) and depth < 2:
                if text[i] == "(":
                    depth += 1
                elif text[i] == ")":
                    depth -= 1
                    if depth == 1:  # the closing paren of allow(...), before ]
                        break
                i += 1
            names.update(LINT.findall(text[m.end() : i]))
    return names


def unknown_on(channel: str, names: set[str], workdir: pathlib.Path) -> set[str]:
    """Names clippy does not know on `channel`."""
    src = workdir / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "lib.rs").write_text(PROBE_CRATE.format(names=", ".join(sorted(names))), encoding="utf-8")
    (workdir / "Cargo.toml").write_text(
        '[package]\nname = "lintprobe"\nversion = "0.0.0"\nedition = "2021"\n\n[workspace]\n',
        encoding="utf-8",
    )
    if shutil.which("cargo") is None:
        print("cargo is not on PATH", file=sys.stderr)
        raise SystemExit(2)
    env = dict(os.environ, RUSTUP_TOOLCHAIN=channel)
    proc = subprocess.run(
        ["cargo", "clippy", "-q", "--offline"],
        cwd=workdir, env=env, capture_output=True, text=True, check=False,
    )
    blob = proc.stdout + proc.stderr
    return set(re.findall(r"unknown lint: `(clippy::[a-z_]+)`", blob))


def main(argv: list[str]) -> int:
    root = pathlib.Path(argv[1] if len(argv) > 1 else ".").resolve()
    channels = os.environ.get("CC_LINT_CHANNELS", "stable:esp").split(":")
    channels = [c for c in channels if c]

    names = collect(root)
    if not names:
        print("[lint-names] no lint names found in allow/expect attributes")
        return 0

    print(f"[lint-names] {len(names)} distinct lint names in allow/expect attributes")
    installed = subprocess.run(
        ["rustup", "toolchain", "list"], capture_output=True, text=True, check=False
    ).stdout

    unknown: dict[str, set[str]] = {}
    for channel in channels:
        if channel not in installed:
            print(
                f"[lint-names] toolchain '{channel}' is not installed; it cannot be "
                f"probed, so the lints it does not know are not being checked. "
                f"Install it, or pass CC_LINT_CHANNELS.",
                file=sys.stderr,
            )
            return 2
        with tempfile.TemporaryDirectory() as tmp:
            unknown[channel] = unknown_on(channel, names, pathlib.Path(tmp))
        missing = sorted(unknown[channel])
        print(f"[lint-names] {channel}: {len(names) - len(missing)}/{len(names)} known")

    # A name is KNOWN if at least one channel knows it, i.e. it is absent from
    # the INTERSECTION of the unknown sets -- not from their union. (Getting this
    # backwards reports almost every real lint as a typo, which is what the first
    # version of this script did.)
    unknown_everywhere = set.intersection(*unknown.values())
    known_anywhere = names - unknown_everywhere
    neither = sorted(unknown_everywhere)
    partial = sorted(known_anywhere)

    # Only the names that are actually absent somewhere are interesting here;
    # a lint every channel knows is not a two-channel hazard.
    split = [n for n in partial if any(n in unknown[c] for c in channels)]
    if split:
        print("[lint-names] known on some but not all channels (fine; this is why")
        print("[lint-names] `unknown_lints = \"allow\"` is set in Cargo.toml):")
        for name in split:
            absent = [c for c in channels if name in unknown[c]]
            print(f"  {name:<44} absent from: {', '.join(absent)}")

    if neither:
        print(
            "\n[lint-names] a lint named in an allow/expect exists on NEITHER "
            "supported channel, so the suppression is a typo or a name that never "
            "existed. It does nothing and hides the real lint behind it:",
            file=sys.stderr,
        )
        for name in neither:
            print(f"  {name}", file=sys.stderr)
        return 1

    print("[lint-names] every lint named in an allow/expect is a real lint")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
